#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {
 'author_email': 'TBD',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'Framework for Unified Systems Engineering and Design of Wind Plants',
 'include_package_data': True,
 'license': 'Apache v. 2.0',
 'name': 'dummies',
 'package_data': {'dummies': []},
 'package_dir': {'': 'src'},
 'packages': ['cobyla', 'cobyla.cobyla', 'conmin', 'conmin.conmin', 'newsumt', 'newsumt.newsumtinterruptible', 'slsqp', 'slsqp.slsqp', 'slsqp.'],
 #'url': '',
 'version': '0.1.0',
 'zip_safe': False}


setup(**kwargs)

